version: '3'

services:
  client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: tulsio-client
    hostname: tulsio-client
    restart: always
    env_file: .env
    environment:
      - APP_API=$APP_API
    ports:
      - "3004:3004"
    networks:
      - tulsioClient

networks:
  tulsioClient:
